name: notes
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2


  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  image_picker: ^1.0.8
  path: ^1.8.3
  geolocator: ^11.1.0
  url_launcher: ^6.2.4
  latlong2: ^0.9.1
  flutter_map: ^6.1.0
  google_maps_flutter: ^2.5.3
  flutter_config: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
